export const POST_CART_ITEM_SUCCESS = 'POST_CART_ITEM_SUCCESS';
export const FETCH_CART_ITEMS_START = 'FETCH_CART_ITEMS_START';
export const FETCH_CART_ITEMS_SUCCESS = 'FETCH_CART_ITEMS_SUCCESS';
export const CHANGE_ITEMS_AMOUNT = 'CHANGE_ITEMS_AMOUNT';
export const DELETE_CART_ITEM = 'DELETE_CART_ITEM';

export const FETCH_PRODUCTS_START = 'FETCH_PRODUCTS_START';
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
export const POST_PRODUCT_SUCCESS = 'POST_PRODUCT_SUCCESS';
export const CHANGE_ORDER = 'CHANGE_ORDER';
